version: "3.2"
services:

  db:
    image: mysql
    ports:
      - '3306:3306'
    restart: always
    volumes:
      - ./mysql/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'fqdb'
      MYSQL_USER: 'conor'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: bash docker-entrypoint.sh
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - ./backend/:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    restart: always
    command : npm start
    volumes:
      - ./frontend/src:/app/frontend/src
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - backend

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db
