import React from 'react'

import { Link } from 'react-router-dom'

import { APP_DEVELOPER_URL, APP_TERMS_URL, COLORS, EMAIL, PROD_BASE_URL } from '../data/constants'

import GenericScreen from './GenericScreen'


const TermsScreen = (props) => {

    const pStyle = {
        textAlign: 'justify',
    }

    const headerStyle = {
        textAlign: 'center',
        marginTop: 40,
    }

    const metas = [
        {idKey: 'property', idValue: 'og:title', updateKey: 'content', updateValue: 'Terms of service | Famous-Quotes.uk'},
        {idKey: 'property', idValue: 'og:description', updateKey: 'content', updateValue: 'Terms and conditions for fair use of Famous-Quotes.uk.'},
        {idKey: 'property', idValue: 'og:image', updateKey: 'content', updateValue: `${PROD_BASE_URL}/share-icon.png`},
        {idKey: 'property', idValue: 'og:url', updateKey: 'content', updateValue: `${PROD_BASE_URL}${APP_TERMS_URL}`},
        {idKey: 'property', idValue: 'og:type', updateKey: 'content', updateValue: 'article'},
        {idKey: 'name', idValue: 'twitter:card', updateKey: 'content', updateValue: 'summary'},
    ]
    const links = [
        {idKey: 'rel', idValue: 'canonical', updateKey: 'href', updateValue: `${PROD_BASE_URL}${APP_TERMS_URL}`},
    ]


    return (
        <GenericScreen metas={metas} links={links} title={'Terms of Service | Famous-Quotes.uk'}>
            <div className='container text-justify mb-5 p-5' style={{maxWidth: 800}}>
                <h1 style={{textAlign: 'center'}}>Terms of Service</h1>
                
                <h2 style={headerStyle}>Personal Abuse</h2>
                <p style={pStyle}>A lot of the content on Famous-Quotes.uk is generated by our users. As such, users are required to abide by the following rules. Failure to do so can lead to a loss of posting privileges, banning from the website altogether, and even legal repercussions if applicable.</p>

                <ul>
                    <li>Users will not post messages direct at other users which are intended to cause offence or emotional distress.</li>
                    <li>Users will not knowingly post false or misleading information on the website.</li>
                </ul>

                <p>The Famous-Quotes.uk admins will be the final arbiters of whether any content is in breach of these rules.</p>

                <h2 style={headerStyle}>Technology Abuse</h2>
                <p style={pStyle}>The website is free to use, and the data has been made available <Link to={APP_DEVELOPER_URL} style={{color: COLORS.linkColor}}>via an API</Link>. However, scraping URLs repeatedly with the perceived intention to create a copy of our database is not permitted. Systems found to be doing so can and will be blocked.</p>
                <p style={pStyle}>If a system has been blocked and you believe it should be reinstated, then email us at <a style={{color: COLORS.linkColor}} href={`mailto:${EMAIL}`}>{EMAIL}</a>. Each case will be treated individually. Needless to say, our decision is final and there is no guarantee of reinstatement.</p>
                <p>It goes without saying that attempts to access our internal systems without prior permission is not allowed. Furthermore, it is illegal under the <a style={{color: COLORS.linkColor}} href='https://www.legislation.gov.uk/ukpga/1990/18/contents'>Computer Misuse Act 1990</a>. The website is run by professional software engineers and where it is possible to trace the source of illegal attempts to access our systems, law enforcement shall be notified.</p>

                <h2 style={headerStyle}>Our promises to you</h2>
                <p style={pStyle}>Famous-Quotes.uk will do everything reasonably within their capability to remove any abusive content as quickly as possible. If abusive content is found, appropriate preventative action will be taken.</p>
                <p>All quotes which are flagged as misattributed will be researched and if found to be correctly flagged, appropriate remedial action will be taken (most likely to update the quote with accurate information).</p>

            </div>
        </GenericScreen>
    )
}

export default TermsScreen