# Generated by Django 3.2 on 2023-02-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_comment_reply_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
