# Generated by Django 3.2 on 2023-02-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_quote_offensive_votes'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpMonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=100)),
                ('user_agent', models.CharField(blank=True, max_length=200, null=True)),
                ('datetime', models.DateTimeField()),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
