# Generated by Django 3.2 on 2023-02-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_ipmonitor'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ipmonitor',
            index=models.Index(fields=['datetime', 'ip_address'], name='quotes_ipmo_datetim_3e45f0_idx'),
        ),
    ]
