# Generated by Django 3.2 on 2023-02-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_ipmonitor_quotes_ipmo_datetim_3e45f0_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpThrottle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ipmonitor',
            name='user_agent',
        ),
    ]
