# Generated by Django 3.2 on 2023-02-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_auto_20230211_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipthrottle',
            name='block_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
