# Generated by Django 3.2 on 2023-03-04 18:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0009_alter_ipthrottle_block_expires'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['user_session', '-created_at']},
        ),
        migrations.AddField(
            model_name='quote',
            name='redirect_quote',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ipthrottle',
            name='block_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 5, 18, 25, 20, 249340, tzinfo=utc), null=True),
        ),
    ]
