# Generated by Django 3.2 on 2023-03-04 21:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0010_auto_20230304_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytic',
            name='action',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='ipthrottle',
            name='block_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 5, 21, 29, 23, 756410, tzinfo=utc), null=True),
        ),
    ]
