# Generated by Django 3.2 on 2023-03-04 21:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0011_auto_20230304_2129'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='analytic',
            name='quotes_anal_session_e03915_idx',
        ),
        migrations.AddField(
            model_name='analytic',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ipthrottle',
            name='block_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 5, 21, 38, 47, 107876, tzinfo=utc), null=True),
        ),
        migrations.AddIndex(
            model_name='analytic',
            index=models.Index(fields=['session_id', 'datetime'], name='quotes_anal_session_c61f87_idx'),
        ),
    ]
